services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILE: prod
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
