server:
  port: 8080
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: base
  security:
    oauth2:
      authorization server:
        issuer: ${SPRING_SERVER_URL}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: false
      mail.smtp.starttls.enable: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/db_money_lover}
    username: ${DATASOURCE_NAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    enabled: true
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK
  webflux:
    static-path-pattern: "/static/**"
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth2-redirect-url: ${SPRING_SERVER_URL}
    docExpansion: none

open:
  api:
    title: Money Lover API Documentation
    version: v1.1.0
    description: API-Service
    serverUrl: ${SPRING_SERVER_URL}
    serverName: Server Test

logging:
  file:
    path: logs/
  level:
    root: WARN
    com.nails.auth: DEBUG
    org.springframework: DEBUG

oauth2-config:
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000
  private-key: ${SECURITY_PRIVATE_KEY}
  public-key: ${SECURITY_PUBLIC_KEY}
  base-url: "http://localhost:8080"
  token-uri: "/api/oauth2/token"
  authorization-uri: "/api/oauth2/authorize"
  token-introspection-uri: "/api/oauth2/introspect"
  token-revocation-uri: "/api/oauth2/revoke"
  redirect-uri: "/api/oauth2/callback"
  consent-page-uri: "/api/oauth2/consent"
  login-uri: "/login"
  logout-uri: "/logout"
  error-uri: "/error"
  callback-uri: "/home"
  registration-uri: "/api/register"
  custom-login-uri: "/api/login"
  forgot-password-uri: "/api/forgot-password"
  request-forgot-password-uri: "/api/request-forgot-password"
